### ISSUE TITLE
Secman V3

### ISSUE THREAD

**Issue by abdfnx** [scmn-dev/secman#155]
## Todo

- [x] convert secman cli from **typescript** to **go**
- [x] move it to production
- [x] update all commands interfaces
- [x] integrate secman core with secman cli.
- [x] use @charmbracelet libraries
- [x] `secman auth` command
- [x] `secman auth logout` command
- [x] `secman auth refresh` command
- [x] `secman delete` command
- [x] `secman docs` command
- [x] `secman generate` command
- [x] `secman info` command
- [x] `secman insert` command
- [x] `secman edit` command
- [x] build **secman lister** TUI interface
- [x] add **secman lister** sidebar viewport
- [x] `secman list` command
- [x] `secman read` command, and build it with [bubble-table](https://github.com/Evertras/bubble-table)
- [x] `secman whoami` command
- [x] upgrade secman web extension to `v1.1.0`
- [x] fix **secman desktop** issues
- [x] `secman doctor` command.
- [x] #68 
- [x] @david-tomson create `SMUI` repo for `secman ui` command
- [x] build `secman ui` command
- [x] update `Secman Core` to `v0.4.0` and add new features
- [x] finish from `secman core cli` (`sc`)
- [x] publish secman cli version `v6.2.0`
- [x] integrate secman with [`tran`](https://github.com/abdfnx/tran) (**in the next version 📦**)
- [x] create new flags to `secman auth login` command (**in the next version 📦**)
- [x] add `--user` flag to `secman whoami` command (**in the next version 📦**)
- [x] add `--tree-view` flag to `secman list` command (**in the next version 📦**)
- [x] create `secman encrypt` command (**in the next version 📦**)
- [x] https://github.com/scmn-dev/desktop/issues/51
- [x] create `w.secman.dev` and `u.secman.dev` urls to install secman cli
- [x] https://github.com/scmn-dev/cli.secman.dev/issues/11

**Comment by abdfnx** [comment]
almost ready

**Comment by david-tomson** [comment]
finally 🥳 We are done with all the work

**Comment by abdfnx** [comment]
we did it

**Comment by abdfnx** [comment]
we'll announce about secman v3 tomorrow

**Comment by abdfnx** [comment]
done
