### ISSUE TITLE
redesign `secman`

### ISSUE THREAD

**Issue by abdfnx** [scmn-dev/secman#84]
Ok, now secman cli doesn't use [**api.secman.dev**](https://api.secman.dev)

and secman cli should login to `secman api` not github

> to be honest, I don't like this cli, we have to make secman cli use our api and database

so, I created a small website to see the next secman

[**secman-v2.secman.dev**](https://secman-v2.secman.dev)

# Secman V2

## List Passwords

<p align="center">
   <img src="https://assets.secman.dev/v2/terminal.svg" alt="new secman"  />
</p>

## Authorize

```bash
$ secman auth

E-Mail: yo@secman.dev
MasterPassword: **********
```

## Insert

```bash
$ secman insert -t/--type login

Type: Login
Title: Expo
URL: expo.dev
Username: SecmanX
Password: ********
Extra:
```

## Read

```bash
$ secman read Expo

Title: Expo
URL: expo.dev
Username: SecmanX
Password: ********
Extra:

# show password

$ secman read Expo --show-password

Title: Expo
URL: expo.io
Username: SecmanX
Password: secman_expo_31137
Extra:
```

## Edit

```bash
$ secman edit Expo

What Do You Want To Change ?

1. Title
> 2. URL
3. Username
4. Password
5. Extra

Enter The New URL: expo.dev

# choose

$ secman edit Expo -e/--extra

Enter The New Extra: expo is a powerfull tool
```

## Generate

```bash
$ secman generate
thlnchhmzdwzura

# with options

$ secman generate -l 10 -n -s -c
~-zEQpYXaK

# -l: Length of the generated password
# -n: Include numbers
# -s: Include symbols
# -c: Include capital-letters

# full

$ secman generate --length 16 --numbers --symbols --capital-letters
+Bu-L^uv-/*gQmN
```

## Commands

- **`auth`**
- **`insert`** | **`new`**
- **`read`** | **`show`**
- **`edit`**
- **`generate`** | **`gen`**
- **`delete`** | **`remove`** | **`rm`**
- **`upgrade`** | **`upg`**
- **`uninstall`** | **`un`**
- **`version`**

## Maybe Added

- **`change-master-password`** | **`cms`**
- **`find`** | **`search`**

## Tasks:

- [x] build beautiful help design
- [x] create `auth` command
- [x] add `read` command
- [x] build `generate` command
- [x] add `insert` cmd
- [x] **build the lister**
- [x] create `edit` command
- [x] create & build secman cli API
- [x] build secman configure.
- [x] make the spinner.
- [x] settings cmd.
- [x] finish from the email sender.
- [x] remove cmd.
- [x] #102
- [x] create `init` command.
- [x] design email.
- [x] #110
- [x] update [**secman.dev**](https://secman.dev) docs
- [x] build `crypto` command.
- [x] `whoami` cmd.
- [x] build `v1` dir.
- [x] `logout` cmd.
- [x] `info` command.
- [x] `init` cmd.
- [x] `update` command.
- [x] `docs` command.
- [x] #106

**Comment by abdfnx** [comment]
now we finished from Secman V2, now we're going to build `Secman V3`
