### ISSUE TITLE
The CheckList

### ISSUE THREAD

**Issue by abdfnx** [scmn-dev/secman#92]
<br>

- [x] improve **secman blog**.

- [x] publish the new release **v5.3.8**.

- [x] update [**gh-api**](https://github.com/secman-team/gh-api).

- [x] build `v1.0.3` version of **secman desktop**.

- [x] update changelog.

- [x] add two docs pages at [**docker.secman.dev**](https://docker.secman.dev) .

- [x] build & publish **secman desktop**.

- [x] publish [**auth.secman.dev**](https://auth.secman.dev)

- [x] add new docs.

- [x] create **support** page.

- [x] finish from [**dsk.secman.dev**](https://d.secman.dev) website.

- [x] upgrade secman website.

- [x] build [extension](https://secman.dev/extension) page

- [x] add **SME** firefox extension
